#!/bin/bash

CFLAGS="-std=c11 -Wall -Werror -g $(pkg-config --cflags sdl2 SDL2_image)"
LINKFLAGS="$(pkg-config --libs sdl2 SDL2_image)"
CFILES="util.c wandrix.c"
gcc -o wand $CFLAGS $CFILES $LINKFLAGS

