#!/bin/bash

CFLAGS="-std=c11 -Wall -Wextra -Werror $(pkg-config --cflags sdl2 SDL2_image)"
LINKFLAGS="$(pkg-config --libs sdl2 SDL2_image)"
CFILES="util.c wandrix.c tiled.c draw.c"
gcc -o wand $CFLAGS -g $CFILES gamemain.c $LINKFLAGS \
  || exit $?
gcc -o utiltest $CFLAGS -O3 $CFILES utiltest.c $LINKFLAGS \
  || exit $?

